blocks: 8
concat_hosts: false
data_path: "/home/massimiliano/data/TI-2016"
demo: false
dim: 512
eager: false
epochs: 5
es: false
group_by_host: true
heads: 8
include_start: false
loss: auto
model: DNS-GT
omega: 0.5
p_mask: 0.08
p_random: 0.01
p_same: 0.01
quick_tb: false
seq_strategy: cluster
seqlen: 32
stride: 1
test_fold: 0
test_partition: 0
tiny: false
