"""Generation of maps on computer vision trained models.

Author: Ronan Hamon <ronan.hamon@ec.europa.eu>
"""
import itertools

import torch

from captum.attr import Occlusion, Saliency, GuidedBackprop
from captum.attr import (
    Saliency,
    IntegratedGradients,
    DeepLift,
    GuidedBackprop,
    GuidedGradCam,
    FeatureAblation,
    InputXGradient
)


def generate_occlusion_maps(
    model, instances, target_label, list_win_size, list_strides
):
    """Generate multiple occlusion maps of a model for a given instance.

    Several occlusion maps are generated by varying the size of the window size
    and the stride. If the stride is higher than the size of the window, the
    occlusion maps is not computed.

    Parameters
    ----------
    mh : TorchModelHandler
        Model handler for the model.
    instances : torch.Tensor
        Batch of instances.
    target_label : int
        Label to consider for the occlusion maps.
    list_win_size : list of int or list of tuple
        List of window sizes to consider. Square window are considered.
    list_strides : list of int or list of tuple
        List of strides to consider. Square strides are considered.

    Returns
    -------
    torch.Tensor
        Occlusion maps for the considered instances.
    """
    if list_win_size is None:
        list_win_size = [5, 20]
    if list_strides is None:
        list_strides = [1, 5]

    # get number of channels
    n_channels = instances.shape[1]

    # get products of parameters
    list_params = list(itertools.product(list_strides, list_win_size))

    # prepare model and data
    model.eval()

    instances = instances.to(model.device)
    target = torch.Tensor([target_label]).long().to(model.device)

    # define occlusion method
    occlusion = Occlusion(model)
    saliency = Saliency(model)
    gbp = GuidedBackprop(model)

    # define container for occlusion maps
    occ_maps = torch.zeros(torch.Size([len(list_params)]) + instances.shape)

    model.logger.info('Start computation of occlusion maps.')
    for idp, (stride, win_size) in enumerate(list_params):

        if stride > win_size:
            continue

        sliding_window_shapes = (n_channels, win_size, win_size)
        strides = (n_channels, stride, stride)

        model.logger.info(f'Win size: {sliding_window_shapes} - Strides: {strides}')

        # occ_maps[idp, ...] = (
        #     occlusion.attribute(
        #         instances,
        #         target=target,
        #         sliding_window_shapes=sliding_window_shapes,
        #         strides=strides,
        #     )
        #     .cpu()
        #     .detach()
        # )
        occ_maps[idp, ...] = gbp.attribute(instances, target=target, abs=False).cpu().detach()

    return occ_maps


def generate_gradient_maps(model, instance, target_label, list_methods, logger):
    """Generate multiple gradient maps of a model for a given instance.

    Several gradient maps are generated by varying the method.

    Parameters
    ----------
    mh : TorchModelHandler
        Model handler for the model.
    instance : torch.Tensor
        Batch of one instance.
    target_label : int
        Label to consider for the occlusion maps.
    list_methods : list of str
        List of methods to use.

    Returns
    -------
    torch.Tensor
        Occlusion maps for the considered instances.
    """
    METHODS = {
        'saliency': Saliency,
        'integrated': IntegratedGradients,
        'guidedbackprop': GuidedBackprop,
        'deeplift': DeepLift,
        'gradcam': GuidedGradCam,
        'featureablation': FeatureAblation,
        'inputxgradient': InputXGradient,
    }

    # prepare model and data
    model.eval()
    instances = instance.to(model.device)
    target = torch.Tensor([target_label]).long().to(model.device)

    # define container for occlusion maps
    grad_maps = torch.zeros(torch.Size([len(list_methods)]) + instances.shape)

    logger.info('Start computation of gradients maps.')
    for idm, method_name in enumerate(list_methods):
        logger.info(f'Method: {method_name}')
        grad_maps[idm, ...] = (
            METHODS[method_name](model)
            .attribute(instances, target=target)
            .cpu()
            .detach()
        )

    return grad_maps
