class Constants:
    _NCLASSES_MALICIOUS_CLASSIFICATION = 2
    _NCLASSES_BOTNET_DETECTION = 11
    _DBSCAN_DEFAULT_PERCENTILE = 50
    _TIMEWINDOW_DELTA_BASE = 8.0
    _TIMEWINDOW_DELTA_MIN = 3.0
    _TIMEWINDOW_DELTA_MAX = 4.0


class CliArgsDefaults:
    GPU = [0]
    SHUFFLE_BS = 1000
